### ISSUE TITLE
如何打赏

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/blog#10]
# 如何打赏

很高兴我写的文章（或我写的工具）对你有帮助，请我喝杯咖啡吧！
## 微信 <a name="wechat"></a>

用微信扫描以下二维码，即可发起转账。

（请核对收款人信息为 `CSS魔法`。另建议在本页留言注明打赏原因。）

[![二维码：微信转账页面](https://cloud.githubusercontent.com/assets/1231359/9754122/54070b0e-56f8-11e5-8301-b53ce6ba08f7.png)](#wechat)
## 支付宝 <a name="alipay"></a>

用支付宝钱包 app 扫描以下二维码，即可发起转账。

（请核对收款账户为 `psd***@gmail.com`。另建议在转账备注中注明打赏原因。）

[![二维码：支付宝钱包付款页面](https://cloud.githubusercontent.com/assets/1231359/3113962/a0840882-e6e8-11e3-97e0-d0de162beb1e.png)](#alipay)
## 常见问题
- **打赏多少？**
  
  小额打赏，一杯咖啡钱就足够了。当然，多多益善，来者不拒。
- **可以留名吗？**
  
  可以留名，而且欢迎留名。在下面评论就可以了。

---

&copy; Creative Commons BY-NC-ND 4.0 &nbsp; | &nbsp; [我要订阅](http://www.cssmagic.net/blog/subscribe) &nbsp; | &nbsp; [我要打赏](http://www.cssmagic.net/blog/donate)

**Comment by cssmagic** [comment]
由于打赏人都不太会主动留名，我自己就厚着脸皮记录一下啦：

* 2017-08-10 · **(佚名)** 通过微信打赏 6.66 元。
* 2017-07-20 · **(佚名)** 通过微信打赏 8.88 元。
* 2017-05-02 · **(佚名)** 通过微信打赏 8.88 元。
* 2017-04-14 · @lanzhiheng 通过微信打赏 20.00 元。
* 2017-01-23 · **(佚名)** 通过微信打赏 8.80 元。
* 2016-09-28 · **(佚名)** 通过微信打赏 27.00 元。
* 2016-09-25 · **陈旭** 通过微信打赏 10.00 元。
* 2016-08-19 · @tolerious 通过微信打赏 5.00 元。
* 2016-06-26 · **火焰莲123** 通过微信打赏 5.60 元。
* 2016-05-14 · **浓浓** 通过支付宝打赏 1.00 元。
* 2016-05-09 · **英子** 通过微信打赏 6.66 元。
* 2016-03-31 · **svon** 通过微信打赏 8.00 元。
* 2016-03-15 · **Laven** 通过微信打赏 0.88 元。
* 2016-02-19 · **ivxpingg(国景)** 通过支付宝转账为 [博客](https://github.com/cssmagic/blog) 项目捐助 1.00 元。
* 2015-10-23 · **browserify** 通过微信红包为[《CSS Secrets》翻译及注解](https://github.com/cssmagic/CSS-Secrets) 项目捐助 10.00 元。
* 2015-10-01 · **smil_ezhou** 通过微信红包为[《CSS Secrets》翻译及注解](https://github.com/cssmagic/CSS-Secrets) 项目捐助 8.88 元。
* 2015-09-16 · @snaketzy 通过微信转账为[《CSS Secrets》翻译及注解](https://github.com/cssmagic/CSS-Secrets) 项目捐助 10.00 元。
* 2015-07-31 · **zhou-yiqun** 通过支付宝转账为 [Oh-My-GitHub](https://github.com/UserScript/Oh-My-GitHub) 项目捐助 10.00 元。
* 2015-07-31 · @tracyzmq 通过支付宝转账为 [Oh-My-GitHub](https://github.com/UserScript/Oh-My-GitHub) 项目捐助 50.00 元。

**Comment by tolerious** [comment]
来支持下，捐了微信里面仅剩的5快钱，钱都被老婆管了，哈哈。

**Comment by cssmagic** [comment]
@tolerious 谢谢支持 :smiley:
