### ISSUE TITLE
[邀请] 魔法哥今日作客掘金 AMA 活动，等待你来提问哦！

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/blog#102]
魔法哥今日作客掘金 AMA 活动。“AMA” 的意思就是 “什么问题都可以问” ，以后没这样的机会了哟 😉

如果你的问题刚好涉及「区块链 DApp」、「CSS」、「开源项目」、「程序员个人品牌」、「技术演讲」、「写作与出版」等领域，我们还可以聊得更深入！

活动页面：
https://juejin.im/pin/5bf2e8856fb9a056783708ee

![juejin-ama-poster](https://user-images.githubusercontent.com/1231359/48825574-b57aaa00-eda2-11e8-8955-f35911965d04.jpg)

**Comment by kalasoo** [comment]
赞
