### ISSUE TITLE
这种方式写博客，是不是有一个可以被恶意投稿的问题？

### ISSUE THREAD

**Issue by programus** [cssmagic/blog#17]
比如我现在写的这一篇。哈哈……

**Comment by Tao-Quixote** [comment]
CSS魔法，非常抱歉，今天下午看了你的github才知道原来可以酱紫做博客。然后刚才突然想到这既然是个项目，那应该可以提issue的，只不过不知道是否需要审核，于是手欠在你的github上试了一下，果然是可以的而且不需要审核，造成不便非常抱歉，请close掉吧，sorry.

**Comment by cssmagic** [comment]
@programus 
不久前 GitHub 已增加删除 issue 的功能，聊胜于无。
