### ISSUE TITLE
Unofficial Stylus org

### ISSUE THREAD

**Issue by kizu** [cssmagic/blog#50]
Hi, @cssmagic! I couldn't find your e-mail, so I'm opening this issue in order to contact you about https://github.com/stylus/

I'm a maintainer for Stylus and we've thought about using the `stylus` org for some time in the past, but didn't “claimed” it yet. But now we're thinking about it more, and would like to know if it is possible for you to transfer the ownership for the @stylus org to us?

I can see that you have mostly placeholder projects there, so there shouldn't be any problems for you in transfering the org I think.

**Comment by cssmagic** [comment]
Big fan of Stylus :)

My Gmail username is `cssmagic.cn`.
